;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        c-electric-paren
        c-electric-slash
        end-of-buffer
        forward-sexp
        helm-confirm-and-exit-minibuffer
        indent-for-tab-command
        kill-region
        other-frame
        ))

(setq mc/cmds-to-run-once
      '(
        View-scroll-half-page-backward
        mouse-buffer-menu
        ))
